import { Link } from "react-router-dom";

const topics = [
  ["Create a note and use the clipboard", "Choose a folder or subfolder, then New note. The note stays in that folder. By default, copied text becomes the title, with line breaks changed to spaces and a 180-character limit. Settings lets you paste into the body instead, or turn clipboard reading off. Empty or blocked clipboard access uses your default title and a blank body. If you start editing while clipboard permission is pending, your changes take priority."],
  ["Organize folders, tags, and notes", "Use the + beside Folders to create a folder, and + subfolder beneath a folder to add a child. Folder actions let you rename, recolor, or delete a folder. Deleting a folder moves its notes to No folder and moves child folders up a level. Change a note’s Folder or Tags fields in the editor, or use its action menu. Tags are separated by commas."],
  ["Right-click and note actions", "Right-click a note or press its ⋯ button for view, edit, rename, duplicate, new note in the same folder, pin, tags, archive/restore, version history, exports, move, and delete. The menu acts on the note you clicked. Use Tab or arrow keys to navigate the menu and Escape to close it. Deleting a note requires confirmation and cannot be undone; archive it if you may want it later."],
  ["Search, sort, and calendar", "Search filters the current folder or view using titles, note text, tags, and attachment names. Combine it with a tag filter, or use Clear filters to reset both. Sort by edited date, creation date, note date, title, length, or attachment count. Pinned first is optional. Calendar places notes by their Note date, falling back to creation date. Folder lists exclude archived notes; find those in Archive. Previous note and Next note in the editor move through the same folder or subfolder using your chosen sort order. The position shows where you are, and buttons disable at the first and last note. Navigation clears search and tag filters so the destination is visible. Archived notes are navigated separately."],
  ["Write, format, and attach files", "Use the editor toolbar for headings, bold, italic, highlights, lists, code, and links. Notebook automatically recognizes clearly marked steps or instructional numbered lists after a short pause and saves the original in History. Disable Automatically detect steps in Settings to use manual formatting only. Switching Steps layout off manually prevents it from automatically returning on that note. For manual lab formatting, add a heading for each major step (or paste Markdown headings and fenced command blocks), then choose Steps layout. It adds numbered circles and a connecting line while keeping your text editable. Use Manage steps to rename a title (press Enter or leave the field to apply), add a step at the end or after another step, duplicate, move up/down, or delete a step. Edit content jumps to the instructions in the note. Check off steps to track progress. Undo last step change reverses the latest structural change if you have not edited the note since; History preserves earlier content. You can delete all steps and start again with Add step. Click Steps layout again to remove the timeline without removing its text. A version snapshot preserves the original text before each layout change. Enter continues a numbered list; Shift+Enter adds a line without another number. Enter on an empty list item ends the list. The Exit list toolbar button adds an unnumbered paragraph after the current item while keeping you inside the same step. Tab indents a list item; Shift+Tab moves it back. Paste screenshots into the body or use the attachment area. Files larger than 5 MB are skipped, and a note has an additional combined attachment limit. Images may be resized for storage. Voice typing depends on browser support. Editor text size can be changed in Settings."],
  ["Autosave, sync, and version history", "Notes save automatically on this device and sync to your signed-in account. Check the sync status for progress or errors; Retry cloud sync is available after an error. Automatic snapshots preserve changed content from the open note at your chosen interval, up to 30 versions. Save version creates a manual snapshot. History restores a version’s title and body; it does not restore attachments or deleted notes. Make a snapshot before restoring if you want to keep the current text."],
  ["Export a note to Flashbolt", "Choose Export to Flashbolt from the note menu or editor footer. Flashbolt opens an unsaved draft with suggested cards, the note title, and the original text for comparison. Edit the questions and answers before choosing Save or Save & study. Until then, no set is created. Draft edits survive refreshes in the same browser tab. Back to note keeps the draft; browser Forward can reopen it. Discard draft returns without creating a set. Only note text is converted, not attachments. Clear term :: definition pairs help the parser produce useful cards."],
  ["Backups and other exports", "Download notebook backup in Settings or Download full backup in a note’s footer saves your notes, folders, attachments, and versions as JSON. Keep it somewhere safe. Restore backup loads a JSON backup after confirmation and replaces the local notebook; signed-in cloud sync may merge existing cloud content afterward. For a single note, use text export from its menu or HTML, plain-text Markdown, and Print / Save PDF in its footer. Browser preferences are stored separately from notebook backups."],
  ["Troubleshooting and settings", "If the clipboard is not used, check Settings and the site’s clipboard permission in your browser, then copy text again. If a note seems missing, check the current folder, search, tag filter, and Archive. If sync fails, keep the page open, download a backup, and retry when connected. Settings are saved in this browser; clearing browser storage removes these preferences. Reset settings restores defaults without deleting notebook content."],
];

export default function NotebookHelp({ returnTo }: { returnTo: string }) {
  return <main className="notebook-settings"><div className="notebook-settings-content">
    <Link to={returnTo}>← Back to Notebook</Link>
    <h1>Notebook help</h1><p>Learn the everyday workflows and find answers when something does not behave as expected.</p>
    <Link to={`/admin-dashboard/private-pages/notebook/settings?returnTo=${encodeURIComponent(returnTo)}`}>Open Notebook settings →</Link>
    <nav className="notebook-help-topics" aria-label="Help topics">{topics.map(([title], index) => <a href={`#notebook-help-${index}`} key={title}>{title}</a>)}</nav>
    {topics.map(([title, text], index) => <section className="notebook-help-topic" id={`notebook-help-${index}`} key={title}><h2>{title}</h2><p>{text}</p></section>)}
  </div></main>;
}
